// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using delopgave.Models;

namespace delopgave.Migrations
{
    [DbContext(typeof(delopgaveContext))]
    [Migration("20190304114225_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("delopgave.Models.Haandvaerker", b =>
                {
                    b.Property<int>("HaandvaerkerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HvAnsaettelsedatao");

                    b.Property<string>("HvEfternavn");

                    b.Property<string>("HvFagomraade");

                    b.Property<string>("HvFornavn");

                    b.HasKey("HaandvaerkerId");

                    b.ToTable("Haandvaerkers");
                });

            modelBuilder.Entity("delopgave.Models.Vaerktoej", b =>
                {
                    b.Property<int>("VtId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LiggerIvkt");

                    b.Property<int?>("VaerktoejskasseVtkId");

                    b.Property<string>("VtAnskaffet");

                    b.Property<string>("VtFabrikat");

                    b.Property<string>("VtModel");

                    b.Property<string>("VtSerienr");

                    b.Property<string>("VtType");

                    b.HasKey("VtId");

                    b.HasIndex("VaerktoejskasseVtkId");

                    b.ToTable("Vaerktoejs");
                });

            modelBuilder.Entity("delopgave.Models.Vaerktoejskasse", b =>
                {
                    b.Property<int>("VtkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HaandvaerkerId");

                    b.Property<string>("VtkAnskaffet");

                    b.Property<string>("VtkEjesAf");

                    b.Property<string>("VtkFabrikat");

                    b.Property<string>("VtkFarve");

                    b.Property<string>("VtkModel");

                    b.Property<string>("VtkSerienummer");

                    b.HasKey("VtkId");

                    b.HasIndex("HaandvaerkerId");

                    b.ToTable("Vaerktoejskasses");
                });

            modelBuilder.Entity("delopgave.Models.Vaerktoej", b =>
                {
                    b.HasOne("delopgave.Models.Vaerktoejskasse")
                        .WithMany("Kasse")
                        .HasForeignKey("VaerktoejskasseVtkId");
                });

            modelBuilder.Entity("delopgave.Models.Vaerktoejskasse", b =>
                {
                    b.HasOne("delopgave.Models.Haandvaerker")
                        .WithMany("Vaerker")
                        .HasForeignKey("HaandvaerkerId");
                });
#pragma warning restore 612, 618
        }
    }
}
