apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: gr8sharedb
  name: gr8sharedb
  namespace: gr8tseis
spec:
  containers:
  - env:
    - name: SA_PASSWORD
      value: F19ItOnk
    - name: ACCEPT_EULA
      value: "Y"
    image: mcr.microsoft.com/mssql/server:2017-latest
    imagePullPolicy: IfNotPresent
    name: gr8sharedb
    ports:
    - containerPort: 1433
      protocol: TCP
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: 8m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File

