apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: gr8sharecontrol
  name: gr8sharecontrol
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: gr8sharecontrol
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gr8sharecontrol
    spec:
      containers:
      - image: docker.io/mromar/sharecontrol:latest
        imagePullPolicy: Always
        name: gr8sharecontrol
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 15m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File