apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: gr8stockbroker
  name: gr8stockbroker
  namespace: gr8tseis
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: gr8stockbroker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gr8stockbroker
    spec:
      containers:
      - image: mromar/stockbroker
        imagePullPolicy: Always
        name: gr8stockbroker
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 8m  
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File