apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-03-14T16:17:45Z
  labels:
    run: gr8stocktransaction
  name: gr8stocktransaction
  namespace: gr8tseis
spec:
  ports:
  - nodePort: 31051
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: gr8stocktransaction
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}