apiVersion: v1
kind: Service
metadata:
  name: gr8traderdb
  namespace: gr8tseis
  resourceVersion: "8312787"
spec:
  ports:
  - nodePort: 31049
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    purpose: gr8traderdb
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}