apiVersion: v1
kind: Service
metadata:
  name: gr8transactiondb
  namespace: gr8tseis
  resourceVersion: "8312787"
spec:
  ports:
  - nodePort: 31047
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    purpose: gr8transactiondb
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}