#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1803 AS base
WORKDIR /app
EXPOSE 60466
EXPOSE 44347

FROM microsoft/dotnet:2.1-sdk-nanoserver-1803 AS build
WORKDIR /src
COPY ["Gr8TSEIS/Gr8TSEIS.csproj", "Gr8TSEIS/"]
RUN dotnet restore "Gr8TSEIS/Gr8TSEIS.csproj"
COPY . .
WORKDIR "/src/Gr8TSEIS"
RUN dotnet build "Gr8TSEIS.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Gr8TSEIS.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Gr8TSEIS.dll"]