version: "3.5"

services:
  db:
    container_name: itonk-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "8082:8082"
    environment:
      MSSQL_DATABASE: itonkdb
      MSSQL_ROOT_PASSWORD: "1234"
      MSSQL_USER: itonkdb
      MSSQL_PASSWORD: "1234"
  
  backend:
    build:
        context: .
        dockerfile: delopgave/bin/Release/netcoreapp2.1/Dockerfile
    depends_on:
        - db
    ports:
        - "8081:8081"

  frontend:
    build:
        context: .
        dockerfile: frontend/bin/Release/netcoreapp2.1/Dockerfile
    depends_on:
        - db
    ports:
        - "8080:8080"
    environment:
        - HOST=backend
        