// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockBroker.Models;

namespace StockBroker.Migrations
{
    [DbContext(typeof(DBmodel))]
    partial class DBmodelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StockBroker.Models.Share", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("SharesForSale");

                    b.Property<Guid>("TraderID");

                    b.Property<decimal>("Value");

                    b.HasKey("ID");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("StockBroker.Models.Trader", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Credit");

                    b.HasKey("ID");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("StockBroker.Models.Transaction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BuyerID");

                    b.Property<Guid>("SellerID");

                    b.Property<Guid>("ShareID");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<decimal>("TransferValue");

                    b.HasKey("ID");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
